### PR TITLE
Add freebsd support

### PR DESCRIPTION
**Pull request by the-eater**
This merge adds support for FreeBSD, tested and working on `bento/freebsd-10.3`

it can install `sshfs` and also loads the fuse kernel module as you need to force it on FreeBSD

### CODE REVIEW

**Comment by dustymabe** [comment]
thanks! i'll try to check this out this weekend. 

Can you please break up the 'whitespace changes' into a separate commit?

**Comment by the-eater** [comment]
Sure! if you want I can fix those in all files :')

**Comment by dustymabe** [comment]
> Sure! if you want I can fix those in all files :')

from what i can see you are just removing trailing whitespace from the end of lines? If that's the case, then I'm ok with it.

**Comment by the-eater** [comment]
It will now also load the fuse kernel module if it isn't loaded and sshfs is installed. this gave issues with rebooting

**Comment by dustymabe** [comment]
hey @the-eater - sorry i didn't make it around to this PR this weekend. Had some things come up. Next weekend is more wide open :)

**Comment by the-eater** [comment]
🙈  No problem, looking forward to hearing more next weekend :)

**Comment by dustymabe** [comment]
looks like this works with `freebsd/FreeBSD-10.3-STABLE` - going to merge this

**Comment by the-eater** [comment]
Thanks! :D

**Comment by the-eater** [comment]
@dustymabe any idea when this will be put in a release? :)

**Comment by dustymabe** [comment]
was hoping to put one out yesterday, but #life - hoping to do one soon because there is some other feature work I want to get into a release as well.

**Comment by the-eater** [comment]
Hey whats, the status? still #life?

**Comment by dustymabe** [comment]
hey @the-eater - yeah, i had a wedding or a trip every weekend in june - that and fedora 26 is upon us! so sorry this is taking so long. my july (after this weekend) is wide open so will get it out. Like I said there is some other feature work i want in, so I want a new release as well :)

**Comment by the-eater** [comment]
np :) thanks for the update

**Pull request merged**
