### PR TITLE
Add note for windows users to use cygwin shell.

### PR DESCRIPTION
**Pull request by henning-flmnn**

### CODE REVIEW

**Comment by geerlingguy** [comment]
Is this plugin not able to work with Cmder? I've spent a lot of time debugging dozens of weird edge case issues with Windows 7/8/10 and Drupal VM, and in almost every case, a workaround seems to work a lot better and require fewer steps than in Cygwin, so I'm loathe to recommend people switch back to Cygwin if they need/want SSHFS mounts.

**Comment by geerlingguy** [comment]
Also, just cross referencing https://github.com/dustymabe/vagrant-sshfs/issues/25

**Comment by dustymabe** [comment]
> Is this plugin not able to work with Cmder?

I don't know anything about Cmder, unfortunately.

**Comment by dustymabe** [comment]
thanks @henning-flmnn!

**Pull request merged**
